# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@2.2.2
        with:
          version: 7
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0
          cache: pnpm
      - name: Install dependencies
        - run: pnpm install --frozen-lockfile
      - name: Lint files
        - run: pnpm lint
      - name: Run typescript
        - run: pnpm tsc --noEmit
